# Generated by Django 5.0.6 on 2024-06-20 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_juego', models.CharField(max_length=100, verbose_name='Nombre')),
                ('genero', models.CharField(max_length=50)),
                ('consola', models.CharField(choices=[('PS4', 'PLAYSTATION 4'), ('PS2', 'PLAYSTATION 2'), ('PS1', 'PLAYSTATION 1'), ('PS3', 'PLAYSTATION 3'), ('PS5', 'PLAYSTATION 5')], max_length=3)),
                ('precio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('stock', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('descripcion', models.TextField()),
                ('foto_juego', models.ImageField(upload_to='juegos', verbose_name='Imagen')),
            ],
        ),
    ]
