# Generated by Django 5.0.6 on 2024-06-22 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS4', 'PLAYSTATION 4'), ('PS3', 'PLAYSTATION 3'), ('PS5', 'PLAYSTATION 5'), ('PS2', 'PLAYSTATION 2'), ('PS1', 'PLAYSTATION 1')], max_length=3),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9)),
                ('ciudad', models.CharField(choices=[('Valparaíso', 'Valparaíso'), ('Concepción', 'Concepción'), ('Santiago', 'Santiago')], max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
