# Generated by Django 5.0.6 on 2024-06-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0003_alter_juego_consola_alter_perfil_ciudad_cartitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS5', 'PLAYSTATION 5'), ('PS1', 'PLAYSTATION 1'), ('PS3', 'PLAYSTATION 3'), ('PS2', 'PLAYSTATION 2'), ('PS4', 'PLAYSTATION 4')], max_length=3),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total_venta', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('enviado', 'Enviado')], default='pendiente', max_length=10)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamewebstore.juego', verbose_name='Juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
