# Generated by Django 5.0.6 on 2024-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0004_alter_juego_consola_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total_venta',
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS5', 'PLAYSTATION 5'), ('PS3', 'PLAYSTATION 3'), ('PS4', 'PLAYSTATION 4'), ('PS1', 'PLAYSTATION 1'), ('PS2', 'PLAYSTATION 2')], max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Valparaíso', 'Valparaíso'), ('Concepción', 'Concepción'), ('Santiago', 'Santiago')], max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('completado', 'Completado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
    ]
