# Generated by Django 5.0.6 on 2024-06-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0005_remove_venta_total_venta_alter_juego_consola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS1', 'PLAYSTATION 1'), ('PS2', 'PLAYSTATION 2'), ('PS4', 'PLAYSTATION 4'), ('PS5', 'PLAYSTATION 5'), ('PS3', 'PLAYSTATION 3')], max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Concepción', 'Concepción'), ('Valparaíso', 'Valparaíso'), ('Santiago', 'Santiago')], max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('ENTREGADO', 'ENTREGADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('PREPARADO', 'PREPARADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
