# Generated by Django 5.0.6 on 2024-06-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0007_alter_juego_consola_alter_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS5', 'PLAYSTATION 5'), ('PS1', 'PLAYSTATION 1'), ('PS3', 'PLAYSTATION 3'), ('PS4', 'PLAYSTATION 4'), ('PS2', 'PLAYSTATION 2')], max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Valparaíso', 'Valparaíso'), ('Santiago', 'Santiago'), ('Concepción', 'Concepción')], max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('PREPARADO', 'PREPARADO'), ('ENTREGADO', 'ENTREGADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
