# Generated by Django 5.0.6 on 2024-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0008_alter_juego_consola_alter_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS3', 'PLAYSTATION 3'), ('PS1', 'PLAYSTATION 1'), ('PS4', 'PLAYSTATION 4'), ('PS2', 'PLAYSTATION 2'), ('PS5', 'PLAYSTATION 5')], max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Concepción', 'Concepción'), ('Santiago', 'Santiago'), ('Valparaíso', 'Valparaíso')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENTREGADO', 'ENTREGADO'), ('ENVIADO', 'ENVIADO'), ('PREPARADO', 'PREPARADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
