# Generated by Django 5.0.6 on 2024-06-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0009_alter_juego_consola_alter_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfil_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS2', 'PLAYSTATION 2'), ('PS4', 'PLAYSTATION 4'), ('PS5', 'PLAYSTATION 5'), ('PS3', 'PLAYSTATION 3'), ('PS1', 'PLAYSTATION 1')], max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Santiago', 'Santiago'), ('Valparaíso', 'Valparaíso'), ('Concepción', 'Concepción')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('ENTREGADO', 'ENTREGADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('PREPARADO', 'PREPARADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
