# Generated by Django 5.0.6 on 2024-07-08 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0010_perfil_perfil_completo_alter_juego_consola_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS4', 'PLAYSTATION 4'), ('PS3', 'PLAYSTATION 3'), ('PS2', 'PLAYSTATION 2'), ('PS1', 'PLAYSTATION 1'), ('PS5', 'PLAYSTATION 5')], max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Concepción', 'Concepción'), ('Valparaíso', 'Valparaíso'), ('Santiago', 'Santiago')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PREPARADO', 'PREPARADO'), ('ENVIADO', 'ENVIADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENTREGADO', 'ENTREGADO'), ('CANCELADO', 'CANCELADO')], default='EN PREPARACIÓN', max_length=30),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
