# Generated by Django 5.0.6 on 2024-07-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewebstore', '0011_alter_juego_consola_alter_perfil_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='juego',
        ),
        migrations.AlterField(
            model_name='juego',
            name='consola',
            field=models.CharField(choices=[('PS1', 'PLAYSTATION 1'), ('PS5', 'PLAYSTATION 5'), ('PS2', 'PLAYSTATION 2'), ('PS3', 'PLAYSTATION 3'), ('PS4', 'PLAYSTATION 4')], max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.CharField(choices=[('Valparaíso', 'Valparaíso'), ('Concepción', 'Concepción'), ('Santiago', 'Santiago')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('ENTREGADO', 'ENTREGADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('PREPARADO', 'PREPARADO'), ('CANCELADO', 'CANCELADO')], default='EN PREPARACIÓN', max_length=30),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamewebstore.juego', verbose_name='Juego')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gamewebstore.venta', verbose_name='Venta')),
            ],
        ),
    ]
